{ pkgs, user, host, ... }:
{
  nixpkgs.config.allowUnfree = true;
  networking.computerName = host;
  networking.hostName = host;
  environment.systemPackages = with pkgs; [
    obsidian
    google-chrome
    git
    wezterm
    alacritty
    neovim
    home-manager
    tmux
    ripgrep
    fd
    bat
    eza
    aerospace
    gnupg
    gnugrep
    maccy
  ];
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    cascadia-code
    dejavu_fonts
    powerline-fonts
    ubuntu-sans-mono
    intel-one-mono
    source-code-pro
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
    liberation_ttf
    fira-code
    fira-code-symbols
    mplus-outline-fonts.githubRelease
    dina-font
  ];
  users.users."${user}" = {
    home = "/Users/${user}";
    shell = "/bin/zsh";
  };
  homebrew = {
    enable = true;
    onActivation.cleanup = "zap";
    casks = [
      "karabiner-elements"
      "intellij-idea-ce"
      "copyq"
      "claude"
    ];
  };
  nix = {
    enable = true;
    extraOptions = ''
      experimental-features = nix-command flakes
    '';
  };
  system = {
    stateVersion = 6;
    primaryUser = user;
    defaults = {
      dock.autohide = true;
      finder.AppleShowAllFiles = true;
      loginwindow.GuestEnabled = false;
      NSGlobalDomain = {
        InitialKeyRepeat = 14;
        KeyRepeat = 2;
        ApplePressAndHoldEnabled = false;
        AppleSpacesSwitchOnActivate = false;
      };
      CustomUserPreferences."org.p0deje.Maccy" = {
        pasteByDefault = false;
        removeFormatting = true;
        avoidTakingFocus = true;

        size = 999;
        historySize = 999;
        imageMaxHeight = 40.0;
        clearOnQuit = false;
        clearSystemClipboard = false;

        searchMode = "regexp";
        searchVisibility = "always";
        sortBy = "lastCopiedAt";
        pinTo = "top";

        popupPosition = "cursor";
        popupScreen = 0;
        showInStatusBar = true;
        menuIcon = "maccy";
        showRecentCopyInMenuBar = false;
        showTitle = true;
        showFooter = false;
        showSearch = true;
        showSpecialSymbols = true;
        previewDelay = 500;

        ignoreEvents = false;
        ignoreAllAppsExceptListed = false;
        ignoredApps = [
          "com.agilebits.onepassword7"
          "com.1password.1password"
          "com.apple.keychainaccess"
        ];
        ignoredPasteboardTypes = [
          "org.nspasteboard.TransientType"
          "org.nspasteboard.ConcealedType"
          "org.nspasteboard.AutoGeneratedType"
          "Pasteboard generator type"
          "de.petermaurer.TransientPasteboardType"
        ];

        playSounds = false;
        saratovSeparator = "\n";

        # ⌘⌃B: carbonKeyCode 11 = B; carbonModifiers 4352 = cmdKey|controlKey
        KeyboardShortcuts_popup = "{\"carbonKeyCode\":11,\"carbonModifiers\":4352}";
      };
    };
  };
}
