{ ... }:
# Zscaler TLS-inspection support for the Lima VM.
#
# Zscaler MITMs HTTPS with its own CA; the VM's traffic NATs through the Mac, so it
# sees that cert too and nix/git/curl fail to verify (cache.nixos.org narinfo errors).
#
# Point nix (client AND daemon — the daemon does substituter downloads) plus git/curl
# at a CA bundle that includes the Zscaler root. Regenerate the bundle on the Mac per
# README.md ("Work with zscalar") and copy it to ~/.zscaler-ca.pem there; the VM reads
# it via the read-only `~` mount. The bundle must be complete (standard roots + Zscaler),
# because *_CERT_FILE replaces the default trust — the Mac's /etc/nix/ca_cert.pem is.
let
  caBundle = "/Users/janmejay.singh/.zscaler-ca.pem";
in {
  # Fail the rebuild early and clearly if the CA bundle is missing, rather than
  # letting nix/git die with opaque TLS errors. Generated by the first-time
  # `home-manager switch` on the Mac (home-manager/addons/zscalar.nix).
  #
  # This is an eval-time assertion, so `#bvmw` rebuilds must pass `--impure`
  # (reading the host path `caBundle` is forbidden in pure flake eval). It runs
  # only here, never at boot — an earlier activation-script `exit 1` aborted boot
  # activation and wedged the guest (lima-guestagent / vsock SSH never came up).
  assertions = [{
    assertion = builtins.pathExists caBundle;
    # pure eval reports a host path as missing, so a forgotten `--impure` trips this too.
    message = "Zscaler CA bundle missing at ${caBundle} (or rebuilt without --impure). See bvm.readme.md.";
  }];

  nix.settings.ssl-cert-file = caBundle;
  systemd.services.nix-daemon.environment.NIX_SSL_CERT_FILE = caBundle;

  environment.variables = {
    NIX_SSL_CERT_FILE = caBundle;
    SSL_CERT_FILE = caBundle;
    REQUEST_CA_BUNDLE = caBundle;
    GIT_SSL_CAINFO = caBundle;
  };
}
