{ ... }:
# Zscaler TLS-inspection support for the Lima VM.
#
# Zscaler MITMs HTTPS with its own CA; the VM's traffic NATs through the Mac, so it
# sees that cert too and nix/git/curl fail to verify (cache.nixos.org narinfo errors).
#
# Point nix (client AND daemon — the daemon does substituter downloads) plus git/curl
# at a CA bundle that includes the Zscaler root. Regenerate the bundle on the Mac per
# README.md ("Work with zscalar") and copy it to ~/.zscaler-ca.pem there; the VM reads
# it via the read-only `~` mount. The bundle must be complete (standard roots + Zscaler),
# because *_CERT_FILE replaces the default trust — the Mac's /etc/nix/ca_cert.pem is.
let
  caBundle = "/Users/janmejay.singh/.zscaler-ca.pem";
in {
  # Fail the rebuild early and clearly if the CA bundle is missing, rather than
  # letting nix/git die with opaque TLS errors. Generated by the first-time
  # `home-manager switch` on the Mac (home-manager/addons/zscalar.nix); checked
  # here at activation (not eval) so the flake stays pure — no `--impure` needed.
  system.activationScripts.zscalarCertCheck.text = ''
    if [ ! -e "${caBundle}" ]; then
      echo "error: Zscaler CA bundle not found at ${caBundle}" >&2
      echo "Run 'home-manager switch --flake .#janmejay@js1' on the Mac first (bvm.readme.md)." >&2
      exit 1
    fi
  '';

  nix.settings.ssl-cert-file = caBundle;
  systemd.services.nix-daemon.environment.NIX_SSL_CERT_FILE = caBundle;

  environment.variables = {
    NIX_SSL_CERT_FILE = caBundle;
    SSL_CERT_FILE = caBundle;
    REQUEST_CA_BUNDLE = caBundle;
    GIT_SSL_CAINFO = caBundle;
  };
}
